GET http://localhost:3005/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3005/books HTTP/1.1
Content-Type: application/json

{
    "title" : "harry"
}

###
PUT http://localhost:3005/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "darktower"
}

###
DELETE http://localhost:3005/books/3 HTTP/1.1

Content-Type: application/json